version: '3.8'

services:
  app:
    image: truecare-solutions-platform  
    build:
      context: .  
    ports:
      - "8080:80"
      - "8081:443" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  