version: '3.8'

services:
  app:
    image: true-care-solutions  
    build:
      context: .  
    ports:
      - "8080:80"
      - "8081:443" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  