services:
  tests:
    image: truecaresolutions-tests
    build:
      context: .
      target: tests
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    entrypoint:
      - dotnet
      - test
      - -c=Release
      - --no-build
      - --logger=trx
      - --results-directory=/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp